disabled_rules:
  - todo
  - nesting
  - multiple_closures_with_trailing_closure
  - large_tuple
  - file_length
  - function_body_length
  - identifier_name

opt_in_rules:
  - closure_spacing
  - missing_docs
  - modifier_order
  - convenience_type
  - pattern_matching_keywords
  - multiline_parameters_brackets
  - multiline_arguments_brackets

custom_rules:
  spaces_over_tabs:
    included: ".*\\.swift"
    name: "Spaces over Tabs"
    regex: "\t"
    message: "Prefer spaces for indents over tabs. See Xcode setting: 'Text Editing' -> 'Indentation'"
    severity: warning