# .github/workflows/run-tests.yml

name: Run ComfyNotch Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'  # change this if you're on something else

      - name: Build & Test
        run: |
          xcodebuild test \
            -scheme ComfyNotch \
            -destination 'platform=macOS' \
            -enableCodeCoverage YES
