name: Run ComfyNotch Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-13  # or macos-14 if you're targeting newer Swift stuff

    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Clean DerivedData (just in case)
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme ComfyNotch \
            -project ComfyNotch.xcodeproj \
            -destination 'platform=macOS' \
            -enableCodeCoverage YES \
            -UseModernBuildSystem=YES \
            -skipPackagePluginValidation
