name: Run ComfyNotch Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Run tests
        run: |
          xcodebuild test \
            -scheme ComfyNotch \
            -project ComfyNotch.xcodeproj \
            -destination 'platform=macOS' \
            -enableCodeCoverage YES \
            -UseModernBuildSystem=YES \
            -skipPackagePluginValidation \
            OTHER_SWIFT_FLAGS="-Xfrontend -disable-module-interface-generation"
